# Generated by Django 5.0.1 on 2024-01-15 23:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, help_text="what does your todo's look like, give it a name", max_length=20),
            preserve_default=False,
        ),
    ]
