# Generated by Django 5.0.1 on 2024-01-18 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0002_task_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='NOTE',
            field=models.CharField(blank=True, help_text='something like a quote, anything that will motivate you', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_1',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_2',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_3',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_4',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_5',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_6',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_7',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
